sudo: required
dist: trusty
language: "node_js"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "iojs"
  - "8"
  - "7"
  - "lts/*"
cache:
  directories: node_modules
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:80
